#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export VISUAL="vim"
export LFS=/mnt/lfs
export GOPATH=/home/dinamyc/Code/go

alias mocp='mocp -T darkdot_theme'

# fish
